import image1 from "../../assets/Rabi-img/istockphoto-1024633584-1024x1024.jpg";
import image2 from "./../../assets/Rabi-img/istockphoto-1061909094-1024x1024.jpg";
import image3 from "./../../assets/Rabi-img/istockphoto-468662606-1024x1024.jpg";
import image4 from "./../../assets/Rabi-img/istockphoto-500479042-1024x1024.jpg";
import image5 from "./../../assets/Rabi-img/istockphoto-953937046-1024x1024.jpg";
import image6 from "./../../assets/Rabi-img/istockphoto-1061909094-1024x1024.jpg";
// import image7 from './../../assets/louis-hansel-phEaeqe555M-unsplash.jpg'
// import image8 from './../../assets/luisa-brimble-vIm26fn_QKg-unsplash.jpg'

const Crops = [
  {
    id: 1,
    fasal: "Rabi",
    image: image1,
    crop_name: "Wheat",
    sowing_period: "November to December",
    climatic_conditions: "Cool and moderate temperatures",
    importance: "Staple food, major contributor to food security",
    other_details:
      "Requires well-drained soil, irrigation during critical stages",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Influences market prices and economic stability",
  },
  {
    id: 2,
    fasal: "Rabi",
    image: image2,
    crop_name: "Barley",
    sowing_period: "November to December",
    harvesting_time: "March to April",
    climatic_conditions: "Adapted to cool temperatures",
    importance: "Used for food, fodder, and malt production",
    other_details: "Tolerant to poor soil conditions",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to economic stability",
  },
  {
    id: 3,
    fasal: "Rabi",
    image: image3,
    crop_name: "Mustard",
    sowing_period: "October to November",
    harvesting_time: "February to March",
    climatic_conditions: "Cool temperatures",
    importance: "Oilseed crop for oil extraction",
    other_details: "Well-suited for well-drained loamy soils",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Affects cooking oil market",
  },
  {
    id: 4,
    fasal: "Rabi",
    image: image4,
    crop_name: "Gram (Chickpea)",
    sowing_period: "November to December",
    harvesting_time: "March to April",
    climatic_conditions: "Cool temperatures",
    importance: "Pulse crop, rich source of protein",
    other_details: "Requires well-drained soil",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to protein market",
  },
  {
    id: 5,
    fasal: "Rabi",
    image: image5,
    crop_name: "Peas",
    sowing_period: "October to December",
    harvesting_time: "February to April",
    climatic_conditions: "Cool temperatures",
    importance: "Vegetable crop used in various dishes",
    other_details: "Sensitive to waterlogging",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to vegetable market",
  },
  {
    id: 6,
    fasal: "Rabi",
    image: image6,
    crop_name: "Lentils (Masoor)",
    sowing_period: "October to November",
    harvesting_time: "March to April",
    climatic_conditions: "Cool temperatures",
    importance: "Pulse crop, rich source of protein",
    other_details: "Adaptable to various soil types",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to protein market",
  },

  {
    id: 7,
    fasal: "kharif_crops",
    image: image5,
    crop_name: "Rice",
    sowing_period: "June to July",
    harvesting_time: "October to November",
    climatic_conditions: "Warm temperatures, high humidity",
    importance: "Staple food for a large population",
    other_details: "Requires flooded or waterlogged conditions",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Influences food prices and economy",
  },
  {
    id: 8,
    fasal: "kharif_crops",
    crop_name: "Maize",
    image: image2,
    sowing_period: "June to July",
    harvesting_time: "September to October",
    climatic_conditions: "Warm temperatures",
    importance: "Used for food, fodder, and industrial purposes",
    other_details: "Well-suited for a variety of soils",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to various industries",
  },
  {
    id: 9,
    fasal: "kharif_crops",
    image: image3,
    crop_name: "Millets",
    sowing_period: "June to July",
    harvesting_time: "September to October",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Diverse group of grains, used for food and fodder",
    other_details: "Adaptable to semi-arid conditions",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to food and fodder markets",
  },
  {
    id: 10,
    fasal: "kharif_crops",
    image: image6,
    crop_name: "Cotton",
    sowing_period: "June to July",
    harvesting_time: "October to December",
    climatic_conditions: "Warm temperatures",
    importance: "Fiber crop used in the textile industry",
    other_details: "Well-suited for loamy soils",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Influences textile industry",
  },
  {
    id: 11,
    fasal: "kharif_crops",
    crop_name: "Sugarcane",
    image: image1,
    sowing_period: "June to July",
    harvesting_time: "October to March",
    climatic_conditions: "Warm temperatures",
    importance: "Source of sugar and other by-products",
    other_details: "Requires well-drained fertile soils",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to sugar and allied industries",
  },
  {
    id: 12,
    fasal: "kharif_crops",
    image: image4,
    crop_name: "Pulses (e.g., pigeon pea)",
    sowing_period: "June to July",
    harvesting_time: "September to October",
    climatic_conditions: "Warm temperatures",
    importance: "Protein-rich pulses for consumption",
    other_details: "Adaptable to a variety of soils",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Contributes to protein market",
  },
  {
    id: 13,
    fasal: "kharif_crops",
    image: image2,
    crop_name: "Oilseeds (e.g., groundnut)",
    sowing_period: "June to July",
    harvesting_time: "October to November",
    climatic_conditions: "Warm temperatures",
    importance: "Oil-rich seeds used for oil extraction",
    other_details: "Well-suited for well-drained soils",
    government_support: "Subsidies, irrigation facilities, crop insurance",
    market_impact: "Affects cooking oil market",
  },

  {
    id: 14,
    image: image5,
    fasal: "zaid_crops",
    crop_name: "Cucumber",
    sowing_period: "April to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Commonly used in salads and culinary dishes",
    other_details: "Requires ample sunlight and water",
    government_support: "Limited support, often grown in kitchen gardens",
    market_impact: "Contributes to fresh vegetable market",
  },
  {
    id: 15,
    image: image3,
    fasal: "zaid_crops",
    crop_name: "Watermelon",
    sowing_period: "March to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Popular summer fruit, consumed fresh",
    other_details: "Requires ample sunlight and water",
    government_support: "Limited support, often grown in open fields",
    market_impact: "Contributes to fresh fruit market",
  },
  {
    id: 16,
    fasal: "zaid_crops",
    crop_name: "Bitter Gourd",
    image: image5,
    sowing_period: "April to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Used in various culinary dishes and traditional medicine",
    other_details: "Requires support for climbing vines",
    government_support: "Limited support, often grown in kitchen gardens",
    market_impact: "Contributes to fresh vegetable market",
  },
  {
    id: 17,
    fasal: "zaid_crops",
    image: image4,
    crop_name: "Muskmelon",
    sowing_period: "March to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Sweet summer fruit, consumed fresh",
    other_details: "Requires ample sunlight and water",
    government_support: "Limited support, often grown in open fields",
    market_impact: "Contributes to fresh fruit market",
  },
  {
    id: 18,
    fasal: "zaid_crops",
    crop_name: "Tomato",
    image: image6,
    sowing_period: "March to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Versatile vegetable used in various dishes",
    other_details: "Requires support for climbing vines",
    government_support: "Limited support, often grown in open fields",
    market_impact: "Contributes to fresh vegetable market",
  },
  {
    id: 19,
    fasal: "zaid_crops",
    image: image1,
    crop_name: "Okra (Ladyfinger)",
    sowing_period: "April to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Used in various culinary dishes",
    other_details: "Requires well-drained soil",
    government_support: "Limited support, often grown in kitchen gardens",
    market_impact: "Contributes to fresh vegetable market",
  },
  {
    id: 18,
    fasal: "puneet",
    crop_name: "Tomato",
    image: image6,
    sowing_period: "March to June",
    harvesting_time: "June to August",
    climatic_conditions: "Warm temperatures, well-drained soil",
    importance: "Versatile vegetable used in various dishes",
    other_details: "Requires support for climbing vines",
    government_support: "Limited support, often grown in open fields",
    market_impact: "Contributes to fresh vegetable market",
  },
];
export default Crops;
